= `backtracie`
:toc:
:toc-placement: macro
:toclevels: 4
:toc-title:

image:https://img.shields.io/badge/Contributor%20Covenant-2.0-4baaaa.svg["Contributor Covenant", link="CODE_OF_CONDUCT.adoc"]
image:https://badge.fury.io/rb/backtracie.svg["Gem Version", link="https://badge.fury.io/rb/backtracie"]
image:https://github.com/ivoanjo/backtracie/actions/workflows/test.yml/badge.svg["CI Status", link="https://github.com/ivoanjo/backtracie/actions/workflows/test.yml"]

[discrete]
== Contents

toc::[]

== Installation

Add this line to your application's `gems.rb` or `Gemfile`:

[source,ruby]
----
gem 'backtracie'
----

And then execute:

[source,bash]
----
$ bundle install
----

Or install it yourself as:

[source,bash]
----
$ gem install backtracie
----

This gem is versioned according to http://semver.org/spec/v2.0.0.html[Semantic Versioning].

== Usage

TODO

== Development

After checking out the repo, run `bundle install` to install dependencies. Then, run `rake spec` to run the tests.

To open a console with the gem loaded, run `bundle console`.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to https://rubygems.org[rubygems.org].

== Feedback and success stories

Your feedback is welcome!

== Contributing

Bug reports and pull requests are welcome on GitLab at https://github.com/ivoanjo/backtracie.

This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the http://contributor-covenant.org[Contributor Covenant] code of conduct.

Maintained with ❤️ by https://ivoanjo.me/[Ivo Anjo].

== Code of Conduct

Everyone interacting in the backtracie project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the link:CODE_OF_CONDUCT.adoc[code of conduct].

== Interesting Links

Here's some gems that are doing similar things to Backtracie:

* https://github.com/tmm1/stackprof: A sampling call-stack profiler for Ruby
* https://github.com/ko1/pretty_backtrace: Pretty your exception backtrace
* https://github.com/Shopify/stack_frames: This library allows backtraces to be captured and accessed without object allocations by leveraging MRI's profile frames API

Other interesting links on this matter:

* https://github.com/ruby/ruby/pull/3299: vm_backtrace.c: let rb_profile_frames show cfunc frames
* https://github.com/ruby/ruby/pull/2713: Fix use of the rb_profile_frames start parameter
* https://github.com/rake-compiler/rake-compiler:  Provide a standard and simplified way to build and package Ruby C and Java extensions using Rake as glue.
* https://github.com/ko1/rubyhackchallenge: "Ruby Hack Challenge" (RHC) is a short guide to hack MRI (Matz Ruby Interpreter) internals
* https://docs.ruby-lang.org/en/3.0.0/doc/extension_rdoc.html: Creating Extension Libraries for Ruby
* https://ruby-hacking-guide.github.io/: Ruby Hacking Guide
  ** This is one of the most through and deep guides out there to the MRI internals. Very detailed and in depth, but outdated.
* http://patshaughnessy.net/ruby-under-a-microscope: Book with a really good introduction to MRI internals.

My blog posts on better backtraces:

* https://ivoanjo.me/blog/2020/07/05/ruby-experiment-include-class-names-in-backtraces/: ruby experiment: include class names in backtraces
* https://ivoanjo.me/blog/2020/07/19/better-backtraces-in-ruby-using-tracepoint/: better backtraces in ruby using tracepoint
