= `backtracist`
:toc:
:toc-placement: macro
:toclevels: 4
:toc-title:

image:https://img.shields.io/badge/Contributor%20Covenant-2.0-4baaaa.svg["Contributor Covenant", link="CODE_OF_CONDUCT.adoc"]
image:https://badge.fury.io/rb/backtracist.svg["Gem Version", link="https://badge.fury.io/rb/backtracist"]

[discrete]
== Contents

toc::[]

== Installation

Add this line to your application's `gems.rb` or `Gemfile`:

[source,ruby]
----
gem 'backtracist'
----

And then execute:

[source,bash]
----
$ bundle install
----

Or install it yourself as:

[source,bash]
----
$ gem install backtracist
----

This gem is versioned according to http://semver.org/spec/v2.0.0.html[Semantic Versioning].

== Usage

TODO

== Development

After checking out the repo, run `bundle install` to install dependencies. Then, run `rake spec` to run the tests.

To open a console with the gem loaded, run `bundle console`.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to https://rubygems.org[rubygems.org].

== Feedback and success stories

Your feedback is welcome!

== Contributing

Bug reports and pull requests are welcome on GitLab at https://github.com/ivoanjo/backtracist.

This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the http://contributor-covenant.org[Contributor Covenant] code of conduct.

Maintained with ❤️ by https://ivoanjo.me/[Ivo Anjo].

== Code of Conduct

Everyone interacting in the backtracist project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the link:CODE_OF_CONDUCT.adoc[code of conduct].
